[theme]
primaryColor = "#4CAF50"        # Green for buttons, sliders
backgroundColor = "#FFFFFF"     # White background
secondaryBackgroundColor = "#F0F2F6"  # Light grey panels
textColor = "#262730"           # Dark grey text
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
